FROM bitnami/spark:3.5.0
LABEL maintainer="Miguel Manuttupa <manuttupa.ligas@gmail>"

COPY spark/jars/*.jar /opt/bitnami/spark/jars/
COPY spark/conf/core-site.xml /opt/bitnami/spark/conf/
COPY spark/conf/hive-site.xml /opt/bitnami/spark/conf/